package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class MainForm extends javax.swing.JFrame {
 private boolean formChanged;
    public MainForm() {
         formChanged=false;
        initComponents();
        setIcon();        
     }

    //bal felső sarokban lévő ikon megváltoztatása; a kép elérési útvonala: AntalA_BlackJack\src\view\res\ikon.jpg
    private void setIcon() {
        Image icon = Toolkit.getDefaultToolkit().getImage("src\\view\\res\\ikon.jpg");
        this.setIconImage(icon);
        //this.setLayout(null); 
    }

    private void fajlValasztas() {
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Megnyitás");
        //filterek beállítása (2 szintű):
        FileNameExtensionFilter filterImage = new FileNameExtensionFilter(
                "*.jpg, *.gif", "jpg", "gif");
        fc.setFileFilter(filterImage);
        FileNameExtensionFilter filterText = new FileNameExtensionFilter(
                "*.txt", "txt");
        fc.setFileFilter(filterText);
        // a projektkönyvtár legyen az aktuális könyvtár:
        fc.setCurrentDirectory(new File(System.getProperty("user.dir")));
        // int result = fc.showOpenDialog(this);
        int valasztas = fc.showSaveDialog(this);
        //ha történik fájlkiválasztás, akkor eltároljuk a fájlt, és az adatait egy változóba mentjük stringként:
        if (valasztas == JFileChooser.APPROVE_OPTION) {
            File kivFajl = fc.getSelectedFile();
            String tartalom = "Fájl neve: " + kivFajl.getPath() + "\nElérése: " + kivFajl.getName();
            //a felugro metódus meghívásával a fájl adatait megjelenítjük a felugró ablakban:
            felugro(tartalom);
        }
    }

    //felugró ablak
    private String felugro(String tartalom) {
        Icon ikon = new ImageIcon("src/view/res/ikon.jpg");
        //a gomb változóban fogjuk eltárolni a felhasználó által adott választ
        int gomb = JOptionPane.showConfirmDialog(rootPane, tartalom, "Kérdés", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, ikon);
        String valasz;
        //ha az OK gombra kattintunk:
        if (gomb == JOptionPane.OK_OPTION) {
            valasz = "OK";
        } else {
            valasz = "Cancel";
        }
        return valasz;    
    }  

     
    
    private void kilepes(){  
        //ha változott a form   
        if(formChanged){
             //ha OK-t nyomtunk a felugró ablakon 
            if((felugro("Biztos kilép?").equals("OK"))) {
                    System.exit(0);             
                } 
         //ha nem változott a form   
        }else{
                System.exit(0);
            }   
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        rbLapokatFelsorol = new javax.swing.JRadioButton();
        rbLapokOsszerteke = new javax.swing.JRadioButton();
        MentesAlso = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miMentes = new javax.swing.JMenuItem();
        miKilepes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        rbKockaztat = new javax.swing.JRadioButtonMenuItem();
        rbNemKockaztat = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlackJack");
        setName(""); // NOI18N
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ellenfél"));

        jLabel3.setText("Lapjai:");

        jLabel4.setText("Stratégiája:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(0, 168, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Játékos"));

        jLabel1.setText("Húzott lap értéke:");

        jButton1.setText("Lapot kér");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Kézben tartott lapok:");

        jButton2.setText("Megáll");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Kilépésnél ment");

        buttonGroup2.add(rbLapokatFelsorol);
        rbLapokatFelsorol.setText("lapokat felsorol");
        rbLapokatFelsorol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbLapokatFelsorolItemStateChanged(evt);
            }
        });
        rbLapokatFelsorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLapokatFelsorolActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbLapokOsszerteke);
        rbLapokOsszerteke.setSelected(true);
        rbLapokOsszerteke.setText("lapok összértéke");
        rbLapokOsszerteke.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbLapokOsszertekeItemStateChanged(evt);
            }
        });

        MentesAlso.setText("Mentés");
        MentesAlso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MentesAlsoMouseClicked(evt);
            }
        });
        MentesAlso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentesAlsoActionPerformed(evt);
            }
        });

        jButton4.setText("Kilépés");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MentesAlso)
                    .addComponent(rbLapokOsszerteke)
                    .addComponent(rbLapokatFelsorol))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rbLapokatFelsorol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbLapokOsszerteke)
                .addGap(18, 18, 18)
                .addComponent(MentesAlso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/res/Blackjack-singlehand.jpg"))); // NOI18N

        mFile.setText("File");
        mFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mFileMouseClicked(evt);
            }
        });
        mFile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mFileKeyPressed(evt);
            }
        });

        miMentes.setText("Mentés");
        miMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMentesActionPerformed(evt);
            }
        });
        mFile.add(miMentes);

        miKilepes.setText("Kilépés");
        miKilepes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miKilepesMousePressed(evt);
            }
        });
        miKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKilepesActionPerformed(evt);
            }
        });
        mFile.add(miKilepes);

        jMenuBar1.add(mFile);

        jMenu2.setText("Stratégia");

        buttonGroup1.add(rbKockaztat);
        rbKockaztat.setText("Kockáztat");
        rbKockaztat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbKockaztatItemStateChanged(evt);
            }
        });
        rbKockaztat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKockaztatActionPerformed(evt);
            }
        });
        jMenu2.add(rbKockaztat);

        buttonGroup1.add(rbNemKockaztat);
        rbNemKockaztat.setSelected(true);
        rbNemKockaztat.setText("Nem kockáztat");
        rbNemKockaztat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbNemKockaztatItemStateChanged(evt);
            }
        });
        jMenu2.add(rbNemKockaztat);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("BlackJack");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbLapokatFelsorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLapokatFelsorolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLapokatFelsorolActionPerformed

    private void MentesAlsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentesAlsoActionPerformed

    }//GEN-LAST:event_MentesAlsoActionPerformed

    private void MentesAlsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentesAlsoMouseClicked
        fajlValasztas();
    }//GEN-LAST:event_MentesAlsoMouseClicked

    private void miMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMentesActionPerformed
        fajlValasztas();
    }//GEN-LAST:event_miMentesActionPerformed

    private void rbKockaztatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKockaztatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbKockaztatActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       kilepes();
    }//GEN-LAST:event_formWindowClosing

    private void mFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mFileMouseClicked
    }//GEN-LAST:event_mFileMouseClicked

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
       
    }//GEN-LAST:event_formWindowStateChanged

    private void miKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKilepesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miKilepesActionPerformed

    private void rbKockaztatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbKockaztatItemStateChanged
//         if (evt.getStateChange() == ItemEvent.SELECTED) {
//        System.out.println("selected");
//    }
//    else if (evt.getStateChange() == ItemEvent.DESELECTED) {
//         System.out.println("deselected");
//    }
         formChanged=true; 
    }//GEN-LAST:event_rbKockaztatItemStateChanged

    private void rbNemKockaztatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNemKockaztatItemStateChanged
         formChanged=true;
    }//GEN-LAST:event_rbNemKockaztatItemStateChanged

    private void rbLapokatFelsorolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbLapokatFelsorolItemStateChanged
         formChanged=true;
    }//GEN-LAST:event_rbLapokatFelsorolItemStateChanged

    private void rbLapokOsszertekeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbLapokOsszertekeItemStateChanged
         formChanged=true;
    }//GEN-LAST:event_rbLapokOsszertekeItemStateChanged

    private void mFileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mFileKeyPressed
    
    }//GEN-LAST:event_mFileKeyPressed

    private void miKilepesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miKilepesMousePressed
        kilepes();
        
    }//GEN-LAST:event_miKilepesMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MentesAlso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem miKilepes;
    private javax.swing.JMenuItem miMentes;
    private javax.swing.JRadioButtonMenuItem rbKockaztat;
    private javax.swing.JRadioButton rbLapokOsszerteke;
    private javax.swing.JRadioButton rbLapokatFelsorol;
    private javax.swing.JRadioButtonMenuItem rbNemKockaztat;
    // End of variables declaration//GEN-END:variables
}
