/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zarodolggyak;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JComboBox;

/**
 *
 * @author AdryA
 */
public class Statisztika extends javax.swing.JFrame {

    private Nevsor nevsor;
    //private HashMap<String, Integer> nevId;

    /**
     * Creates new form
     */
    public Statisztika() {
        initComponents();
        nevsor = new Nevsor();

        keziAdatRogzites(nevsor);
        nevsor.felvesz("emberek.txt");

        nemSzerintComboba('F', cbFiuk); //betölti a neveket a comboBoxba nem szerint
        nemSzerintComboba('L', cbLanyok); //betölti a neveket a comboBoxba nem szerint

        // DefaultComboBoxModel dml = new DefaultComboBoxModel();
//        for (int i = 0; i < nevsor.getEmberLista().size(); i++) {
//            dml.addElement(nevsor.getEmberLista().get(i).getNev());
//        }
//        cbLanyok.setModel(dml);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBal = new javax.swing.JPanel();
        pnBalAlso = new javax.swing.JPanel();
        lbLegidosebbCim = new javax.swing.JLabel();
        lbOsszkorCim = new javax.swing.JLabel();
        lbHatEveCim = new javax.swing.JLabel();
        lbLegidosebb = new javax.swing.JLabel();
        lbOsszKor = new javax.swing.JLabel();
        lbHatEveDolg = new javax.swing.JLabel();
        rbLany = new javax.swing.JRadioButton();
        rbFiu = new javax.swing.JRadioButton();
        pnLanyok = new javax.swing.JPanel();
        cbLanyok = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        panelJobb = new javax.swing.JPanel();
        pnFiuk = new javax.swing.JPanel();
        lbFiukCim = new javax.swing.JLabel();
        cbFiuk = new javax.swing.JComboBox<>();
        panelJobbKozep = new javax.swing.JPanel();
        lbKorCim = new javax.swing.JLabel();
        lbMiotaDCim = new javax.swing.JLabel();
        lbKor = new javax.swing.JLabel();
        lbMiotaDolg = new javax.swing.JLabel();
        chbMindkettoNem = new javax.swing.JCheckBox();
        btnMent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dolgozók");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelBal.setToolTipText("");
        panelBal.setName(""); // NOI18N
        panelBal.setLayout(new java.awt.BorderLayout());

        pnBalAlso.setBorder(javax.swing.BorderFactory.createTitledBorder("Összesítő"));

        lbLegidosebbCim.setText("Legidősebb:");

        lbOsszkorCim.setText("Összes kor:");

        lbHatEveCim.setText("6 éve dolgozó:");

        buttonGroup1.add(rbLany);
        rbLany.setText("Lány");
        rbLany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLanyActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFiu);
        rbFiu.setText("Fiú");
        rbFiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFiuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBalAlsoLayout = new javax.swing.GroupLayout(pnBalAlso);
        pnBalAlso.setLayout(pnBalAlsoLayout);
        pnBalAlsoLayout.setHorizontalGroup(
            pnBalAlsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBalAlsoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnBalAlsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBalAlsoLayout.createSequentialGroup()
                        .addComponent(rbLany)
                        .addGap(18, 18, 18)
                        .addComponent(rbFiu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnBalAlsoLayout.createSequentialGroup()
                        .addGroup(pnBalAlsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbLegidosebbCim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbOsszkorCim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbHatEveCim, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(pnBalAlsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbLegidosebb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbOsszKor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbHatEveDolg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        pnBalAlsoLayout.setVerticalGroup(
            pnBalAlsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBalAlsoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnBalAlsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLany)
                    .addComponent(rbFiu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(pnBalAlsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLegidosebbCim)
                    .addComponent(lbLegidosebb))
                .addGap(18, 18, 18)
                .addGroup(pnBalAlsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOsszkorCim)
                    .addComponent(lbOsszKor))
                .addGap(18, 18, 18)
                .addGroup(pnBalAlsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHatEveCim)
                    .addComponent(lbHatEveDolg))
                .addGap(30, 30, 30))
        );

        panelBal.add(pnBalAlso, java.awt.BorderLayout.PAGE_END);

        cbLanyok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLanyokActionPerformed(evt);
            }
        });

        jLabel1.setText("Lányok");

        javax.swing.GroupLayout pnLanyokLayout = new javax.swing.GroupLayout(pnLanyok);
        pnLanyok.setLayout(pnLanyokLayout);
        pnLanyokLayout.setHorizontalGroup(
            pnLanyokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLanyokLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbLanyok, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnLanyokLayout.setVerticalGroup(
            pnLanyokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLanyokLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnLanyokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbLanyok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        panelBal.add(pnLanyok, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBal);

        lbFiukCim.setText("Fiúk");

        cbFiuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFiukLayout = new javax.swing.GroupLayout(pnFiuk);
        pnFiuk.setLayout(pnFiukLayout);
        pnFiukLayout.setHorizontalGroup(
            pnFiukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFiukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFiukCim)
                .addGap(28, 28, 28)
                .addComponent(cbFiuk, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnFiukLayout.setVerticalGroup(
            pnFiukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFiukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFiukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFiukCim)
                    .addComponent(cbFiuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelJobbKozep.setBorder(javax.swing.BorderFactory.createTitledBorder("Adatok"));

        lbKorCim.setText("Kor:");

        lbMiotaDCim.setText("Mióta dolgozik:");

        javax.swing.GroupLayout panelJobbKozepLayout = new javax.swing.GroupLayout(panelJobbKozep);
        panelJobbKozep.setLayout(panelJobbKozepLayout);
        panelJobbKozepLayout.setHorizontalGroup(
            panelJobbKozepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJobbKozepLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelJobbKozepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbKorCim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMiotaDCim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(panelJobbKozepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbKor, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(lbMiotaDolg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJobbKozepLayout.setVerticalGroup(
            panelJobbKozepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJobbKozepLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(panelJobbKozepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKorCim)
                    .addComponent(lbKor))
                .addGap(18, 18, 18)
                .addGroup(panelJobbKozepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMiotaDCim)
                    .addComponent(lbMiotaDolg))
                .addGap(37, 37, 37))
        );

        chbMindkettoNem.setText("Mindkettő nem");
        chbMindkettoNem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbMindkettoNemActionPerformed(evt);
            }
        });

        btnMent.setText("Ment");
        btnMent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMentMouseClicked(evt);
            }
        });
        btnMent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelJobbLayout = new javax.swing.GroupLayout(panelJobb);
        panelJobb.setLayout(panelJobbLayout);
        panelJobbLayout.setHorizontalGroup(
            panelJobbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJobbLayout.createSequentialGroup()
                .addGroup(panelJobbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelJobbLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelJobbLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelJobbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelJobbLayout.createSequentialGroup()
                                .addComponent(chbMindkettoNem)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(panelJobbKozep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelJobbLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(pnFiuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelJobbLayout.setVerticalGroup(
            panelJobbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJobbLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pnFiuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelJobbKozep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbMindkettoNem)
                .addGap(18, 18, 18)
                .addComponent(btnMent)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(panelJobb);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbLanyokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLanyokActionPerformed
        nevAlapjanAdatok(cbLanyok);

    }//GEN-LAST:event_cbLanyokActionPerformed

    private void cbFiukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiukActionPerformed
        nevAlapjanAdatok(cbFiuk);        // TODO add your handling code here:
    }//GEN-LAST:event_cbFiukActionPerformed

    private void rbLanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLanyActionPerformed
        if (this.isActive()) {
            //először a mindkét nemre vonatkozó checkboxot ki nem jelölt állapotra kell állítani 
            chbMindkettoNem.setSelected(false); 
            szamitasok('L');
        }
    }//GEN-LAST:event_rbLanyActionPerformed

    private void rbFiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFiuActionPerformed
        if (this.isActive()) {
            chbMindkettoNem.setSelected(false);
            szamitasok('F');
        }
    }//GEN-LAST:event_rbFiuActionPerformed

    private void chbMindkettoNemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbMindkettoNemActionPerformed
        if (this.isActive()) {
            //először mindkét rádiógombot (fiú / lány) ki nem jelölt állapotra kell állítani 
            rbFiu.setSelected(false);  
            rbLany.setSelected(false);
            szamitasok(' ');
        }       // TODO add your handling code here:
    }//GEN-LAST:event_chbMindkettoNemActionPerformed

    private void btnMentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMentActionPerformed

    private void btnMentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMentMouseClicked
        String tartalom="";
        if (chbMindkettoNem.isSelected()) {
            tartalom= tartalomFajlba('L')+tartalomFajlba('F');
            System.out.println(tartalom);
       }
            if (rbLany.isSelected()) {
               tartalom= tartalomFajlba('L');
           
            }
            if (rbFiu.isSelected()) {
                tartalom= tartalomFajlba('F');
           
            }
             fajlbaIr("dolgozok.txt", tartalom);
           
        
    }//GEN-LAST:event_btnMentMouseClicked
    public void keziAdatRogzites(Nevsor nevsor) {
        nevsor.felvesz(new Ember("Eszter", 20, 'L', 2));
        nevsor.felvesz(new Ember("Kati", 18, 'L'));
        nevsor.felvesz(new Ember("Zénó", 21, 'F'));
        nevsor.felvesz(new Ember("Gábor", 50, 'F', 30));
    }

    //betölti a neveket a comboBoxba nem szerint
    public void nemSzerintComboba(char nem, JComboBox comboNev) {
        comboNev.addItem("-Válassz nevet--");
        for (int i = 0; i < nevsor.getEmberLista().size(); i++) {
            if (nevsor.getEmberLista().get(i).getNem() == nem) {
                comboNev.addItem(nevsor.getEmberLista().get(i).getNev());
                //nevId.put(nevsor.getEmberLista().get(i).getNev(),i);
            }
        }
    }

//név alapján megkeresi az adott ember objektumot 
    public Ember nevAlapjanKeres(String nev) {
        Ember ember = null;
        for (int i = 0; i < nevsor.getEmberLista().size(); i++) {
            if (nevsor.getEmberLista().get(i).getNev().equals(nev)) {
                ember = nevsor.getEmberLista().get(i);
            }
        }
        return ember;
    }

//összkor, maxkor és legalább 6 éve dolgozók a megfelelő labelekbe töltése  
    public void szamitasok(char nem) {
        int maxKor = 0;
        int osszKor = 0;
        int minHatEveDolg = 0;
        if (!(nem == ' ')) {
            for (int i = 0; i < nevsor.getEmberLista().size(); i++) {
                //nemenként
                if (nevsor.getEmberLista().get(i).getNem() == nem) {
                    osszKor += nevsor.getEmberLista().get(i).getKor();
                    if (nevsor.getEmberLista().get(i).getMunkToltEv() >= 6) {
                        minHatEveDolg++;
                    }
                    if (nevsor.getEmberLista().get(i).getKor() > maxKor) {
                        maxKor = nevsor.getEmberLista().get(i).getKor();
                    }
                }
            }
        } else { //összesen, nemtől függetlenül
            for (int i = 0; i < nevsor.getEmberLista().size(); i++) {
                osszKor += nevsor.getEmberLista().get(i).getKor();
                if (nevsor.getEmberLista().get(i).getKor() > maxKor) {
                    maxKor = nevsor.getEmberLista().get(i).getKor();
                }
                if (nevsor.getEmberLista().get(i).getMunkToltEv() >= 6) {
                    minHatEveDolg++;
                }
            }
        }

        lbLegidosebb.setText(Integer.toString(maxKor));
        lbOsszKor.setText(Integer.toString(osszKor));
        lbHatEveDolg.setText(Integer.toString(minHatEveDolg));

    }

    //név alapján megkeresi az adott Ember objektumot a listában
    public void nevAlapjanAdatok(JComboBox comboNev) {
        int index = comboNev.getSelectedIndex();
        if (index > 0) {
            String nev = (String) comboNev.getItemAt(index);
            Ember ember = nevAlapjanKeres(nev);
            lbKor.setText(Integer.toString(ember.getKor()));
            lbMiotaDolg.setText(Integer.toString(ember.getMunkToltEv()));
        }
    }
    
    
    
    /*FÁJLBA ÍRÁS*/
    public void fajlbaIr(String fileNev, String tartalom) {
        try {
            FileWriter myWriter = new FileWriter(fileNev);                     
            myWriter.write(tartalom.trim());
            myWriter.close();
            System.out.println("Fájlba írás sikeres!");
        } catch (IOException e) {
            e.getMessage();
        }
    }
    
    
    public String tartalomFajlba(char nem){
    String str="";    
    String cim="";
            if (nem=='L') {
                cim="Lányok";
            } else if (nem=='F'){
                cim="Fiúk";
            }
    str += cim+ "\n"
            + lbLegidosebbCim.getText() + " " + lbLegidosebb.getText()  + "\n" 
            + lbOsszkorCim.getText()  + " " +lbOsszKor.getText()  + "\n" 
            + lbHatEveCim.getText()  + " " +lbHatEveDolg.getText()  + "\n";    
    return str;
    }
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statisztika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statisztika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statisztika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statisztika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statisztika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbFiuk;
    private javax.swing.JComboBox<String> cbLanyok;
    private javax.swing.JCheckBox chbMindkettoNem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbFiukCim;
    private javax.swing.JLabel lbHatEveCim;
    private javax.swing.JLabel lbHatEveDolg;
    private javax.swing.JLabel lbKor;
    private javax.swing.JLabel lbKorCim;
    private javax.swing.JLabel lbLegidosebb;
    private javax.swing.JLabel lbLegidosebbCim;
    private javax.swing.JLabel lbMiotaDCim;
    private javax.swing.JLabel lbMiotaDolg;
    private javax.swing.JLabel lbOsszKor;
    private javax.swing.JLabel lbOsszkorCim;
    private javax.swing.JPanel panelBal;
    private javax.swing.JPanel panelJobb;
    private javax.swing.JPanel panelJobbKozep;
    private javax.swing.JPanel pnBalAlso;
    private javax.swing.JPanel pnFiuk;
    private javax.swing.JPanel pnLanyok;
    private javax.swing.JRadioButton rbFiu;
    private javax.swing.JRadioButton rbLany;
    // End of variables declaration//GEN-END:variables
}
